---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/auth/login":
    post:
      summary: Authenticates a user
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: User authenticated
        '401':
          description: Invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: admin@rakamin.com
                password:
                  type: string
                  example: password123
  "/api/v1/health":
    get:
      summary: Checks the health of the API
      tags:
      - Health
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                required:
                - status
  "/api/v1/portfolios/{id}/fitgap":
    parameters:
    - name: id
      in: path
      description: ID Portfolio
      required: true
      schema:
        type: string
    post:
      summary: Generate Fit/Gap Analysis
      tags:
      - Portfolios
      security:
      - Bearer: []
      parameters: []
      responses:
        '202':
          description: Fit/Gap successfully generated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                vacancy_id:
                  type: string
              required:
              - vacancy_id
  "/api/v1/portfolios/{id}/regenerate_fitgap":
    parameters:
    - name: id
      in: path
      description: ID Portfolio
      required: true
      schema:
        type: string
    post:
      summary: Regenerate Fit/Gap Analysis
      tags:
      - Portfolios
      security:
      - Bearer: []
      parameters: []
      responses:
        '202':
          description: Fit/Gap successfully regenerated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                vacancy_id:
                  type: string
              required:
              - vacancy_id
  "/api/v1/portfolios/{id}/fitgap/{vacancy_id}":
    parameters:
    - name: id
      in: path
      description: ID Portfolio
      required: true
      schema:
        type: string
    - name: vacancy_id
      in: path
      description: ID Vacancy
      required: true
      schema:
        type: string
    get:
      summary: Retrieves Fit/Gap Analysis result
      tags:
      - Portfolios
      security:
      - Bearer: []
      responses:
        '200':
          description: Displays analysis result
  "/api/v1/sessions/{id}/portfolio":
    parameters:
    - name: id
      in: path
      description: ID Session
      required: true
      schema:
        type: string
    get:
      summary: Retrieves Portfolio details by Session
      tags:
      - Sessions
      security:
      - Bearer: []
      responses:
        '200':
          description: Displays portfolio details
  "/api/v1/vacancies":
    get:
      summary: Retrieves a list of vacancies
      tags:
      - Vacancies
      security:
      - Bearer: []
      responses:
        '200':
          description: List of vacancies
          content:
            application/json:
              schema:
                type: object
                properties:
                  vacancies:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        role_title:
                          type: string
                        culture_dimensions:
                          type: string
                        competency_expectations:
                          type: string
                        created_by:
                          type: integer
                        created_at:
                          type: string
                          format: date-time
                        updated_at:
                          type: string
                          format: date-time
                  meta:
                    type: object
                required:
                - vacancies
                - meta
        '403':
          description: Tenant not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3001
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
